version: '3.4'

services:

  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
      network: host
    image: todo-client
    ports:
      - 3000:3000
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
      network: host
    image: todo-server
    ports:
      - 3001:3001
    environment:
      MONGODB_ADMINUSERNAME: root
      MONGODB_ADMINPASSWORD: example
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example